"""Added token table

Revision ID: 415d3e4f3612
Revises: 2a71122f630e
Create Date: 2022-05-11 14:31:04.922853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415d3e4f3612'
down_revision = '2a71122f630e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('token', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokens')
    # ### end Alembic commands ###
